service: PersonalAPIPersonal
variablesResolutionMode: null

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'sa-east-1'}
  stackName: ApiCV-${self:provider.stage}
  deploymentPrefix: projects
  httpApi:
    cors: true
    disableDefaultEndpoint: false
    metrics: true
    useProviderTags: true
  tags:
    Project: PortfolioAPI
    Environment: ${opt:stage,'dev'}
  logs:
    httpApi: true
    frameworkLambda: true
  environment:
    REGION: ${self:provider.region}
    NODE_ENV: dev



plugins:
  - serverless-plugin-typescript
  - serverless-offline-sqs
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-dotenv-plugin

package:
  individually: true
  include:
    - config/.env.${self:provider.stage}

functions:
  projects-get-all:
    handler: src/handler.projectGetAll
    events:
      - httpApi:
          path: /api/v3/my/project
          method: get

  project-create:
    handler: src/handler.projectCreate
    events:
      - httpApi:
          path: /api/v3/my/project
          method: post

  programmingLanguage-get-all:
    handler: src/handler.programmingLanguageGetAll
    events:
      - httpApi:
          path: /api/v3/my/programming-language
          method: get

  programmingLanguage-create:
    handler: src/handler.programmingLanguageCreate
    events:
      - httpApi:
          path: /api/v3/my/programming-language
          method: post

  framework-get-all:
    handler: src/handler.frameworkGetAll
    events:
      - httpApi:
          path: /api/v3/my/framework
          method: get

  framework-create:
    handler: src/handler.frameworkCreate
    events:
      - httpApi:
          path: /api/v3/my/framework
          method: post

  library-get-all:
    handler: src/handler.librariesGetAll
    events:
      - httpApi:
          path: /api/v3/my/libraries
          method: get

  library-create:
    handler: src/handler.librariesCreate
    events:
      - httpApi:
          path: /api/v3/my/libraries
          method: post

custom:
  serverless-offline:
    httpPort: 5000
    lambdaPort: 5004
  dotenv:
    path: config/.env.${self:provider.stage}




